-- ==========================================
-- 车牌查询系统 - 数据库初始化脚本
-- ==========================================

-- 1. 创建车辆信息表
CREATE TABLE vehicle_infos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name VARCHAR(100) NOT NULL,
  license_plate VARCHAR(20) NOT NULL UNIQUE,
  phone VARCHAR(20),
  department VARCHAR(50),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 创建索引（提高查询性能）
CREATE INDEX idx_vehicle_infos_license_plate ON vehicle_infos(license_plate);
CREATE INDEX idx_vehicle_infos_department ON vehicle_infos(department);
CREATE INDEX idx_vehicle_infos_created_at ON vehicle_infos(created_at DESC);

-- 3. 创建复合索引（优化常用查询）
CREATE INDEX idx_vehicle_infos_department_created ON vehicle_infos(department, created_at DESC);

-- 4. 启用RLS（行级安全）- 可选
ALTER TABLE vehicle_infos ENABLE ROW LEVEL SECURITY;

-- 5. 创建允许所有操作的策略（开发阶段）
CREATE POLICY "Allow all access" ON vehicle_infos
FOR ALL USING (true);

-- 6. 插入示例数据（可选，用于测试）
INSERT INTO vehicle_infos (owner_name, license_plate, phone, department, description) VALUES
('张三', '京A12345', '13800138000', '教师车辆', '黑色轿车'),
('李四', '京A54321', '13900139000', '后勤车辆', '白色面包车'),
('王五', '京B67890', '13700137000', '集团车辆', '灰色SUV'),
('赵六', '京C98765', '13600136000', '临时车辆', '蓝色货车'),
('孙七', '京D11223', '13500135000', '家长车辆', '红色MPV'),
('周八', '京A44556', '13400134000', '教师车辆', '银色轿车'),
('吴九', '京B77889', '13300133000', '后勤车辆', '白色货车'),
('郑十', '京C99001', '13200132000', '集团车辆', '黑色商务车');

-- 7. 创建查询视图（可选，方便查看数据统计）
CREATE VIEW vehicle_stats AS
SELECT
  department,
  COUNT(*) as vehicle_count,
  MIN(created_at) as first_added,
  MAX(created_at) as last_added
FROM vehicle_infos
GROUP BY department
ORDER BY vehicle_count DESC;

-- 8. 验证数据
SELECT * FROM vehicle_infos LIMIT 5;
SELECT * FROM vehicle_stats;

-- ==========================================
-- 完成！
-- ==========================================
-- 1. 点击 "Run" 执行此SQL脚本
-- 2. 确认看到 "Success" 提示
-- 3. 然后继续下一步：获取配置信息
